#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent.set_env("DDCLIENT_HOST", data["ddclient_host"])
agent.set_env("DDCLIENT_LOGIN", data["ddclient_login"])
agent.set_env("DDCLIENT_PASSWORD", data["ddclient_password"])
agent.set_env("DDCLIENT_PROTOCOL", data["ddclient_protocol"])
agent.set_env("DDCLIENT_SERVER", data["ddclient_server"])
agent.set_env("HTTP2HTTPS", data["http2https"])
