#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "ddclient_host": os.environ["DDCLIENT_HOST"],
    "ddclient_login": os.environ["DDCLIENT_LOGIN"],
    "ddclient_password": agent.read_envfile("password.env")["DDCLIENT_PASSWORD"],
    "ddclient_protocol": os.environ["DDCLIENT_PROTOCOL"],
    "ddclient_server": os.environ["DDCLIENT_SERVER"],
    "ddclient_daemon": os.environ["DDCLIENT_DAEMON"],
    "ddclient_ipv6": os.environ["DDCLIENT_IPV6"],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
