#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["ddclient_host"] = os.getenv("DDCLIENT_HOST","")
config["ddclient_login"] = os.getenv("DDCLIENT_LOGIN","")
config["ddclient_password"] = os.getenv("DDCLIENT_PASSWORD","")
config["ddclient_protocol"] = os.getenv("DDCLIENT_PROTOCOL","")
config["ddclient_server"] = os.getenv("DDCLIENT_SERVER","")
config["http2https"] = os.getenv("HTTP2HTTPS","") == "True"

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
