#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "DDCLIENT_HOST",
        "DDCLIENT_LOGIN",
        "DDCLIENT_PROTOCOL",
        "DDCLIENT_SERVER",
        "DDCLIENT_DAEMON",
        "DDCLIENT_IPV6"
    ]:
    agent.set_env(evar, original_environment[evar])
