#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "ddclient_host": renv["DDCLIENT_HOST"],
    "ddclient_login": renv["DDCLIENT_LOGIN"],
    "ddclient_password": renv["DDCLIENT_PASSWORD"],
    "ddclient_protocol": renv["DDCLIENT_PROTOCOL"],
    "ddclient_server": renv["DDCLIENT_SERVER"],
    "ddclient_daemon": renv["DDCLIENT_DAEMON"],
    "ddclient_ipv6": renv["DDCLIENT_IPV6"],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
